# config.make generated by configure script
POCO_CONFIG = Linux
POCO_BASE = /home/leon/MyVideoCollection/poco
POCO_BUILD = /home/leon/MyVideoCollection/poco
POCO_PREFIX = /usr/local
POCO_FLAGS = 
OMIT = Data
LINKMODE = SHARED
export POCO_CONFIG
export POCO_BASE
export POCO_BUILD
export POCO_PREFIX
export POCO_FLAGS
export LINKMODE
